field_size:
- 1000
- 1000
N: 30
mission_time_s: 1200
uav:
  speed_mps: 12
  battery_Wh: 60
  P_move_W: 180
  P_hover_W: 140
  P_tx_W: 2
radio:
  bandwidth_Hz: 1000000
  noise_W: 1.0e-09
  pathloss_exponent: 2.7
  snr_threshold_linear: 3.0
  comm_radius_m: 220
payload_bits: 1642018
policy: RR
beta: 0.8327943313963473
gamma: 1.1048551704061231
alpha: 0.44964660007858476
seed: 2081897854
