field_size:
- 1000
- 1000
N: 30
mission_time_s: 1200
uav:
  mass_kg: 1.5
  g: 9.81
  rotor_radius_m: 0.15
  disc_area_m2: 0.0707
  blade_tip_speed: 140.0
  rotor_solidity: 0.05
  P0: 10.0
  Pi: null
  d0: 0.3
  air_density: 1.225
  speed_mps: 12
  battery_Wh: 60
radio:
  bandwidth_Hz: 1000000
  noise_W: 1.0e-09
  pathloss_exponent: 2.7
  snr_threshold_linear: 3.0
  comm_radius_m: 220
tx:
  P_circuit_W: 1.0
  amp_efficiency: 0.4
  P_out_W: 1.0
payload_bits: 1750692
policy: AWN
beta: 1.2078715177638442
gamma: 1.2342206994275535
alpha: 0.5282565212572689
seed: 1200
