field_size:
- 1000
- 1000
N: 30
mission_time_s: 1200
uav:
  speed_mps: 12
  battery_Wh: 60
  P_move_W: 180
  P_hover_W: 140
  P_tx_W: 2
radio:
  bandwidth_Hz: 1000000
  noise_W: 1.0e-09
  pathloss_exponent: 2.7
  snr_threshold_linear: 3.0
  comm_radius_m: 220
payload_bits: 1666220
policy: AWN
beta: 0.9566821671416714
gamma: 1.1703233200695344
alpha: 0.533895125117732
seed: 474160949
